/*
 * Books API
 *
 * API for Books
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {

	Message string `json:"message,omitempty"`
}
