/*
 * Books API
 *
 * API for Books
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BookIdBody struct {

	Title string `json:"title,omitempty"`

	Author string `json:"author,omitempty"`

	Publisher string `json:"publisher,omitempty"`
}
