/*
 * Books API
 *
 * API for Books
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/book/",
		Index,
	},

	Route{
		"BookIdDelete",
		strings.ToUpper("Delete"),
		"/book/book/{id}",
		BookIdDelete,
	},

	Route{
		"BookIdGet",
		strings.ToUpper("Get"),
		"/book/book/{id}",
		BookIdGet,
	},

	Route{
		"BookIdPut",
		strings.ToUpper("Put"),
		"/book/book/{id}",
		BookIdPut,
	},

	Route{
		"BooksGet",
		strings.ToUpper("Get"),
		"/book/books",
		BooksGet,
	},

	Route{
		"BooksPost",
		strings.ToUpper("Post"),
		"/book/books",
		BooksPost,
	},
}
